name: Actualizar Tasas BCV

on:
  schedule:
    # 1. ACTUALIZACIONES DE TARDE (Lunes a Viernes)
    # 4:30 PM, 5:30 PM y 6:30 PM HORA VENEZOLANA VET (20:30, 21:30, 22:30 UTC)
    # Aquí es donde el script detecta la tasa nueva y la guarda en "next"
    - cron: '30 20,21,22 * * 1-5'

    # 2. ROTACIÓN DE MEDIANOCHE HORA VENEZOLANA (Martes a Sábado)
    # 12:30 AM VET (04:30 AM UTC)
    # Aquí el script ve que ya es "hoy" y mueve "next" a "current"
    - cron: '30 4 * * 2-6'
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script de scraping
        run: python update_bcv.py

      - name: Guardar cambios en el JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tasa_actual.json
          git commit -m "Actualización tasas BCV: $(date)" || echo "No hay cambios para commitear"
          git push
