name: Actualizar Tasas BCV

on:
  schedule:
  # Se ejecutará a las 20:30, 21:30 y 22:30 UTC (4:30, 5:30 y 6:30 PM VET)
    - cron: '30 20,21,22 * * 1-5'
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script de scraping
        run: python update_bcv.py

      - name: Guardar cambios en el JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tasa_actual.json
          git commit -m "Actualización tasas BCV: $(date)" || echo "No hay cambios para commitear"
          git push
